app = 'automation-hiring-challenge'
primary_region = 'sin'

[build]

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  BROADCAST_DRIVER = 'log'
  CACHE_DRIVER = 'array'
  QUEUE_CONNECTION = 'sync'
  SUPERVISOR_PHP_USER = 'sail'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  interval = '10s'
  timeout = '2s'
  grace_period = '5s'
  method = 'GET'
  path = '/'
  protocol = 'http'
  tls_skip_verify = false

# Services handled by http_service above

# Build configuration that handles both Laravel backend and React frontend
[build.args]
  NODE_VERSION = "20"
  PHP_VERSION = "8.2"
